### ISSUE TITLE
cannot npm install

### ISSUE THREAD

**Issue by mochechan** [sivann-tw/hiver-iot-kit-ble#7]
~/hiver-iot-kit-ble$ npm install
npm ERR! Linux 4.4.0-97-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: bshep-plugin-sivann-nineaxis@1.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.0.4, 0.0.3, 0.0.2, 0.0.1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'hiver-iot-kit-ble'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/a/hiver-iot-kit-ble/npm-debug.log

**Comment by hedywings** [comment]
Hi @mochechan,

The problem is due to the wrong version of dependency packages, we have fixed the problem and it can be installed properly now.
